// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvk0MrUllvH98BZq_eOFg7Ujm_BlW3bqc',
    appId: '1:157190576363:web:0bb8ef2acffbbab26286ae',
    messagingSenderId: '157190576363',
    projectId: 'count-down-7de35',
    authDomain: 'count-down-7de35.firebaseapp.com',
    storageBucket: 'count-down-7de35.appspot.com',
    measurementId: 'G-NP1RH7EVHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zaukBQQT-QD6QHda_DjyaVTV3KE_9kw',
    appId: '1:157190576363:android:9513d9dd9bdbe5126286ae',
    messagingSenderId: '157190576363',
    projectId: 'count-down-7de35',
    storageBucket: 'count-down-7de35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfX-je-_YF7h6uJ9WvycMei9fJpw44cJo',
    appId: '1:157190576363:ios:3093947b8491baf96286ae',
    messagingSenderId: '157190576363',
    projectId: 'count-down-7de35',
    storageBucket: 'count-down-7de35.appspot.com',
    iosBundleId: 'com.example.countdownEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfX-je-_YF7h6uJ9WvycMei9fJpw44cJo',
    appId: '1:157190576363:ios:3093947b8491baf96286ae',
    messagingSenderId: '157190576363',
    projectId: 'count-down-7de35',
    storageBucket: 'count-down-7de35.appspot.com',
    iosBundleId: 'com.example.countdownEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvk0MrUllvH98BZq_eOFg7Ujm_BlW3bqc',
    appId: '1:157190576363:web:3df597ccfa7893736286ae',
    messagingSenderId: '157190576363',
    projectId: 'count-down-7de35',
    authDomain: 'count-down-7de35.firebaseapp.com',
    storageBucket: 'count-down-7de35.appspot.com',
    measurementId: 'G-QRFFJTJNTY',
  );
}
